fron:
  build: ../web/
  container_name: front
  ports:
    - "4200:80"

php:
  build: ./
  container_name: meu-php
  ports:
    - "9000:80"
  links:
    - db

db:
  image: mysql:latest
  container_name: meu-mysql-php
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_VERSION=latest
